name: orbit
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/apoleon33/orbit


environment:
  sdk: ^3.8.2

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  dotenv: ^4.2.0
  tint: ^2.0.1
  colorgram: 1.0.1
  http: ^1.4.0
  image: ^4.5.4
  dartpy: ^0.0.5
  ffi: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
